### PR TITLE
Adds got agent option

### PR DESCRIPTION
**Pull request by ryanholte**

### CODE REVIEW

**Comment by TLadd** [comment]
Resolves https://github.com/recombee/node-api-client/issues/6.

Being able to use keepAlive is pretty important to allow reusing connections instead of needing to reestablish every call. 

```
import { Agent } from "node:http";
import { Agent as HttpsAgent } from "node:https";

const httpAgent = new Agent({
  keepAlive: true,
});
const httpsAgent = new HttpsAgent({
  keepAlive: true,
});
const recombeeClient = new ApiClient(
  RECOMBEE_DATABASE_ID,
  RECOMBEE_PRIVATE_TOKEN,
  {
    agent: {
      http: httpAgent,
      https: httpsAgent,
    }
  }
);
```

**Comment by OndraFiedler** [comment]
@ryanholte @TLadd Thanks for the Pull Request!

I am just wondering: wouldn't the simpler:
```js
new ApiClient(
  RECOMBEE_DATABASE_ID,
  RECOMBEE_PRIVATE_TOKEN,
  {
    agent: agent
  }
);
```
be sufficient?

Sending the HTTP requests (instead of HTTPS) is rather rare and has to be explicitly configured using the `protocol` option.

**Comment by TLadd** [comment]
@OndraFiedler We were just matching [got's API](https://github.com/sindresorhus/got/blob/main/source/core/options.ts#L1125) so it ends up being a simple passthrough. It could be changed to what you're saying though and accept a single agent which is either set on the `http` or `https` key in the object passed to `got` based on its type (HttpAgent or HttpsAgent). We can make that change if it is your preference.

**Comment by OndraFiedler** [comment]
@TLadd Thanks for the explanation! It makes sense to keep the format of the `got` API.

**Pull request merged**
